using System;
using System.Collections.Generic;
using System.Linq;
using SmartBot.Plugins.API;
using SmartBotProfiles;

/* Explanation on profiles :
 * 
 * All the values defined in profiles are percentage modifiers, it means that it will affect base profile's default values.
 * 
 * parameters.GlobalSpellsModifier ---> Modifier applied to all spells no matter what they are. The higher is the modifier, the less likely the AI will be to play the spell
 * parameters.GlobalMinionsModifier ---> Modifier applied to all minions no matter what they are. The higher is the modifier, the less likely the AI will be to play the minion
 * 
 * parameters.GlobalAggroModifier ---> Modifier applied to enemy's health value, the higher it is, the more aggressive will be the AI
 * parameters.GlobalDefenseModifier ---> Modifier applied to friendly's health value, the higher it is, the more hp conservative will be the AI
 * 
 * parameters.SpellsModifiers ---> You can set individual modifiers to each spells there, those are ADDED to the GLOBAL modifiers !!
 * parameters.MinionsModifiers ---> You can set individual modifiers to each minions there, those are ADDED to the GLOBAL modifiers !!
 * 
 */

namespace SmartBot.Profiles
{
    [Serializable]
    public class ShameShaman : Profile
    {
        #region Collectable Cards
        private const Card.Cards Wisp = Card.Cards.CS2_231;           // [0 mana][1/1] Wisp 
        private const Card.Cards MurlocTinyfin = Card.Cards.LOEA10_3;     // [0 mana][1/1] Murloc Tinyfin 
        private const Card.Cards TargetDummy = Card.Cards.GVG_093;        // [0 mana][0/2] Target Dummy 
        private const Card.Cards Moonfire = Card.Cards.CS2_008;           // [0 mana][0/0] Moonfire 
        private const Card.Cards AncestralHealing = Card.Cards.CS2_041;           // [0 mana][0/0] Ancestral Healing 
        private const Card.Cards Backstab = Card.Cards.CS2_072;           // [0 mana][0/0] Backstab 
        private const Card.Cards HuntersMark = Card.Cards.CS2_084;        // [0 mana][0/0] Hunter's Mark 
        private const Card.Cards Innervate = Card.Cards.EX1_169;          // [0 mana][0/0] Innervate 
        private const Card.Cards TotemicMight = Card.Cards.EX1_244;           // [0 mana][0/0] Totemic Might 
        private const Card.Cards SacrificialPact = Card.Cards.NEW1_003;       // [0 mana][0/0] Sacrificial Pact 
        private const Card.Cards Shadowstep = Card.Cards.EX1_144;         // [0 mana][0/0] Shadowstep 
        private const Card.Cards Preparation = Card.Cards.EX1_145;        // [0 mana][0/0] Preparation 
        private const Card.Cards Silence = Card.Cards.EX1_332;        // [0 mana][0/0] Silence 
        private const Card.Cards InnerRage = Card.Cards.EX1_607;          // [0 mana][0/0] Inner Rage 
        private const Card.Cards CircleofHealing = Card.Cards.EX1_621;        // [0 mana][0/0] Circle of Healing 
        private const Card.Cards GoldshireFootman = Card.Cards.CS1_042;           // [1 mana][1/2] Goldshire Footman 
        private const Card.Cards Voidwalker = Card.Cards.CS2_065;         // [1 mana][1/3] Voidwalker 
        private const Card.Cards LightsJustice = Card.Cards.CS2_091;          // [1 mana][1/4] Light's Justice 
        private const Card.Cards MurlocRaider = Card.Cards.CS2_168;           // [1 mana][2/1] Murloc Raider 
        private const Card.Cards StonetuskBoar = Card.Cards.CS2_171;          // [1 mana][1/1] Stonetusk Boar 
        private const Card.Cards ElvenArcher = Card.Cards.CS2_189;        // [1 mana][1/1] Elven Archer 
        private const Card.Cards NorthshireCleric = Card.Cards.CS2_235;           // [1 mana][1/3] Northshire Cleric 
        private const Card.Cards TimberWolf = Card.Cards.DS1_175;         // [1 mana][1/1] Timber Wolf 
        private const Card.Cards VoodooDoctor = Card.Cards.EX1_011;           // [1 mana][2/1] Voodoo Doctor 
        private const Card.Cards GrimscaleOracle = Card.Cards.EX1_508;        // [1 mana][1/1] Grimscale Oracle 
        private const Card.Cards BloodImp = Card.Cards.CS2_059;           // [1 mana][0/1] Blood Imp 
        private const Card.Cards SouthseaDeckhand = Card.Cards.CS2_146;           // [1 mana][2/1] Southsea Deckhand 
        private const Card.Cards YoungDragonhawk = Card.Cards.CS2_169;        // [1 mana][1/1] Young Dragonhawk 
        private const Card.Cards AbusiveSergeant = Card.Cards.CS2_188;        // [1 mana][2/1] Abusive Sergeant 
        private const Card.Cards Lightwarden = Card.Cards.EX1_001;        // [1 mana][1/2] Lightwarden 
        private const Card.Cards YoungPriestess = Card.Cards.EX1_004;         // [1 mana][2/1] Young Priestess 
        private const Card.Cards ArgentSquire = Card.Cards.EX1_008;           // [1 mana][1/1] Argent Squire 
        private const Card.Cards AngryChicken = Card.Cards.EX1_009;           // [1 mana][1/1] Angry Chicken 
        private const Card.Cards WorgenInfiltrator = Card.Cards.EX1_010;          // [1 mana][2/1] Worgen Infiltrator 
        private const Card.Cards LeperGnome = Card.Cards.EX1_029;         // [1 mana][2/1] Leper Gnome 
        private const Card.Cards Secretkeeper = Card.Cards.EX1_080;           // [1 mana][1/2] Secretkeeper 
        private const Card.Cards DustDevil = Card.Cards.EX1_243;          // [1 mana][3/1] Dust Devil 
        private const Card.Cards FlameImp = Card.Cards.EX1_319;           // [1 mana][3/2] Flame Imp 
        private const Card.Cards Shieldbearer = Card.Cards.EX1_405;           // [1 mana][0/4] Shieldbearer 
        private const Card.Cards MurlocTidecaller = Card.Cards.EX1_509;           // [1 mana][1/2] Murloc Tidecaller 
        private const Card.Cards ManaWyrm = Card.Cards.NEW1_012;      // [1 mana][1/3] Mana Wyrm 
        private const Card.Cards HungryCrab = Card.Cards.NEW1_017;    // [1 mana][1/2] Hungry Crab 
        private const Card.Cards BloodsailCorsair = Card.Cards.NEW1_025;      // [1 mana][1/2] Bloodsail Corsair 
        private const Card.Cards PitSnake = Card.Cards.LOE_010;           // [1 mana][2/1] Pit Snake 
        private const Card.Cards TunnelTrogg = Card.Cards.LOE_018;        // [1 mana][1/3] Tunnel Trogg 
        private const Card.Cards SirFinleyMrrgglton = Card.Cards.LOE_076;         // [1 mana][1/3] Sir Finley Mrrgglton 
        private const Card.Cards ReliquarySeeker = Card.Cards.LOE_116;        // [1 mana][1/1] Reliquary Seeker 
        private const Card.Cards CursedBlade = Card.Cards.LOE_118;        // [1 mana][2/3] Cursed Blade 
        private const Card.Cards ZombieChow = Card.Cards.FP1_001;         // [1 mana][2/3] Zombie Chow 
        private const Card.Cards Webspinner = Card.Cards.FP1_011;         // [1 mana][1/1] Webspinner 
        private const Card.Cards Undertaker = Card.Cards.FP1_028;         // [1 mana][1/2] Undertaker 
        private const Card.Cards Shadowbomber = Card.Cards.GVG_009;           // [1 mana][2/1] Shadowbomber 
        private const Card.Cards Cogmaster = Card.Cards.GVG_013;          // [1 mana][1/2] Cogmaster 
        private const Card.Cards Warbot = Card.Cards.GVG_051;         // [1 mana][1/3] Warbot 
        private const Card.Cards ClockworkGnome = Card.Cards.GVG_082;         // [1 mana][2/1] Clockwork Gnome 
        private const Card.Cards TwilightWhelp = Card.Cards.BRM_004;          // [1 mana][2/1] Twilight Whelp 
        private const Card.Cards DragonEgg = Card.Cards.BRM_022;          // [1 mana][0/2] Dragon Egg 
        private const Card.Cards Buccaneer = Card.Cards.AT_029;           // [1 mana][2/1] Buccaneer 
        private const Card.Cards BraveArcher = Card.Cards.AT_059;         // [1 mana][2/1] Brave Archer 
        private const Card.Cards LowlySquire = Card.Cards.AT_082;         // [1 mana][1/2] Lowly Squire 
        private const Card.Cards TournamentAttendee = Card.Cards.AT_097;          // [1 mana][2/1] Tournament Attendee 
        private const Card.Cards InjuredKvaldir = Card.Cards.AT_105;          // [1 mana][2/4] Injured Kvaldir 
        private const Card.Cards GadgetzanJouster = Card.Cards.AT_133;        // [1 mana][1/2] Gadgetzan Jouster 
        private const Card.Cards HolySmite = Card.Cards.CS1_130;          // [1 mana][0/0] Holy Smite 
        private const Card.Cards MindVision = Card.Cards.CS2_003;         // [1 mana][0/0] Mind Vision 
        private const Card.Cards PowerWordShield = Card.Cards.CS2_004;        // [1 mana][0/0] Power Word: Shield 
        private const Card.Cards Claw = Card.Cards.CS2_005;           // [1 mana][0/0] Claw 
        private const Card.Cards MirrorImage = Card.Cards.CS2_027;        // [1 mana][0/0] Mirror Image 
        private const Card.Cards FrostShock = Card.Cards.CS2_037;         // [1 mana][0/0] Frost Shock 
        private const Card.Cards RockbiterWeapon = Card.Cards.CS2_045;        // [1 mana][0/0] Rockbiter Weapon 
        private const Card.Cards Corruption = Card.Cards.CS2_063;         // [1 mana][0/0] Corruption 
        private const Card.Cards DeadlyPoison = Card.Cards.CS2_074;           // [1 mana][0/0] Deadly Poison 
        private const Card.Cards SinisterStrike = Card.Cards.CS2_075;         // [1 mana][0/0] Sinister Strike 
        private const Card.Cards BlessingofMight = Card.Cards.CS2_087;        // [1 mana][0/0] Blessing of Might 
        private const Card.Cards Execute = Card.Cards.CS2_108;        // [1 mana][0/0] Execute 
        private const Card.Cards Tracking = Card.Cards.DS1_184;           // [1 mana][0/0] Tracking 
        private const Card.Cards ArcaneShot = Card.Cards.DS1_185;         // [1 mana][0/0] Arcane Shot 
        private const Card.Cards ArcaneMissiles = Card.Cards.EX1_277;         // [1 mana][0/0] Arcane Missiles 
        private const Card.Cards MortalCoil = Card.Cards.EX1_302;         // [1 mana][0/0] Mortal Coil 
        private const Card.Cards Soulfire = Card.Cards.EX1_308;           // [1 mana][0/0] Soulfire 
        private const Card.Cards Humility = Card.Cards.EX1_360;           // [1 mana][0/0] Humility 
        private const Card.Cards HandofProtection = Card.Cards.EX1_371;           // [1 mana][0/0] Hand of Protection 
        private const Card.Cards Whirlwind = Card.Cards.EX1_400;          // [1 mana][0/0] Whirlwind 
        private const Card.Cards InnerFire = Card.Cards.CS1_129;          // [1 mana][0/0] Inner Fire 
        private const Card.Cards IceLance = Card.Cards.CS2_031;           // [1 mana][0/0] Ice Lance 
        private const Card.Cards ColdBlood = Card.Cards.CS2_073;          // [1 mana][0/0] Cold Blood 
        private const Card.Cards Conceal = Card.Cards.EX1_128;        // [1 mana][0/0] Conceal 
        private const Card.Cards NobleSacrifice = Card.Cards.EX1_130;         // [1 mana][0/0] Noble Sacrifice 
        private const Card.Cards EyeforanEye = Card.Cards.EX1_132;        // [1 mana][0/0] Eye for an Eye 
        private const Card.Cards Redemption = Card.Cards.EX1_136;         // [1 mana][0/0] Redemption 
        private const Card.Cards Naturalize = Card.Cards.EX1_161;         // [1 mana][0/0] Naturalize 
        private const Card.Cards LightningBolt = Card.Cards.EX1_238;          // [1 mana][0/0] Lightning Bolt 
        private const Card.Cards EarthShock = Card.Cards.EX1_245;         // [1 mana][0/0] Earth Shock 
        private const Card.Cards ForkedLightning = Card.Cards.EX1_251;        // [1 mana][0/0] Forked Lightning 
        private const Card.Cards PowerOverwhelming = Card.Cards.EX1_316;          // [1 mana][0/0] Power Overwhelming 
        private const Card.Cards BlessingofWisdom = Card.Cards.EX1_363;           // [1 mana][0/0] Blessing of Wisdom 
        private const Card.Cards Repentance = Card.Cards.EX1_379;         // [1 mana][0/0] Repentance 
        private const Card.Cards Upgrade = Card.Cards.EX1_409;        // [1 mana][0/0] Upgrade! 
        private const Card.Cards ShieldSlam = Card.Cards.EX1_410;         // [1 mana][0/0] Shield Slam 
        private const Card.Cards BestialWrath = Card.Cards.EX1_549;           // [1 mana][0/0] Bestial Wrath 
        private const Card.Cards Savagery = Card.Cards.EX1_578;           // [1 mana][0/0] Savagery 
        private const Card.Cards SacredTrial = Card.Cards.LOE_027;        // [1 mana][0/0] Sacred Trial 
        private const Card.Cards RavenIdol = Card.Cards.LOE_115;          // [1 mana][0/0] Raven Idol 
        private const Card.Cards Avenge = Card.Cards.FP1_020;         // [1 mana][0/0] Avenge 
        private const Card.Cards LightoftheNaaru = Card.Cards.GVG_012;        // [1 mana][0/0] Light of the Naaru 
        private const Card.Cards ArcaneBlast = Card.Cards.AT_004;         // [1 mana][0/0] Arcane Blast 
        private const Card.Cards PowerWordGlory = Card.Cards.AT_013;          // [1 mana][0/0] Power Word: Glory 
        private const Card.Cards LivingRoots = Card.Cards.AT_037;         // [1 mana][0/0] Living Roots 
        private const Card.Cards FlashHeal = Card.Cards.AT_055;           // [1 mana][0/0] Flash Heal 
        private const Card.Cards CompetitiveSpirit = Card.Cards.AT_073;           // [1 mana][0/0] Competitive Spirit 
        private const Card.Cards FieryWarAxe = Card.Cards.CS2_106;        // [2 mana][3/2] Fiery War Axe 
        private const Card.Cards RiverCrocolisk = Card.Cards.CS2_120;         // [2 mana][2/3] River Crocolisk 
        private const Card.Cards FrostwolfGrunt = Card.Cards.CS2_121;         // [2 mana][2/2] Frostwolf Grunt 
        private const Card.Cards KoboldGeomancer = Card.Cards.CS2_142;        // [2 mana][2/2] Kobold Geomancer 
        private const Card.Cards BloodfenRaptor = Card.Cards.CS2_172;         // [2 mana][3/2] Bloodfen Raptor 
        private const Card.Cards BluegillWarrior = Card.Cards.CS2_173;        // [2 mana][2/1] Bluegill Warrior 
        private const Card.Cards NoviceEngineer = Card.Cards.EX1_015;         // [2 mana][1/1] Novice Engineer 
        private const Card.Cards AcidicSwampOoze = Card.Cards.EX1_066;        // [2 mana][3/2] Acidic Swamp Ooze 
        private const Card.Cards Succubus = Card.Cards.EX1_306;           // [2 mana][4/3] Succubus 
        private const Card.Cards MurlocTidehunter = Card.Cards.EX1_506;           // [2 mana][2/1] Murloc Tidehunter 
        private const Card.Cards FlametongueTotem = Card.Cards.EX1_565;           // [2 mana][0/3] Flametongue Totem 
        private const Card.Cards IronbeakOwl = Card.Cards.CS2_203;        // [2 mana][2/1] Ironbeak Owl 
        private const Card.Cards BloodmageThalnos = Card.Cards.EX1_012;           // [2 mana][1/1] Bloodmage Thalnos 
        private const Card.Cards AncientWatcher = Card.Cards.EX1_045;         // [2 mana][4/5] Ancient Watcher 
        private const Card.Cards YouthfulBrewmaster = Card.Cards.EX1_049;         // [2 mana][3/2] Youthful Brewmaster 
        private const Card.Cards ManaAddict = Card.Cards.EX1_055;         // [2 mana][1/3] Mana Addict 
        private const Card.Cards SunfuryProtector = Card.Cards.EX1_058;           // [2 mana][2/3] Sunfury Protector 
        private const Card.Cards CrazedAlchemist = Card.Cards.EX1_059;        // [2 mana][2/2] Crazed Alchemist 
        private const Card.Cards PintSizedSummoner = Card.Cards.EX1_076;          // [2 mana][2/2] Pint-Sized Summoner 
        private const Card.Cards MadBomber = Card.Cards.EX1_082;          // [2 mana][3/2] Mad Bomber 
        private const Card.Cards LootHoarder = Card.Cards.EX1_096;        // [2 mana][2/1] Loot Hoarder 
        private const Card.Cards LorewalkerCho = Card.Cards.EX1_100;          // [2 mana][0/4] Lorewalker Cho 
        private const Card.Cards DefiasRingleader = Card.Cards.EX1_131;           // [2 mana][2/2] Defias Ringleader 
        private const Card.Cards DireWolfAlpha = Card.Cards.EX1_162;          // [2 mana][2/2] Dire Wolf Alpha 
        private const Card.Cards StormforgedAxe = Card.Cards.EX1_247;         // [2 mana][2/3] Stormforged Axe 
        private const Card.Cards Lightwell = Card.Cards.EX1_341;          // [2 mana][0/5] Lightwell 
        private const Card.Cards ArgentProtector = Card.Cards.EX1_362;        // [2 mana][2/2] Argent Protector 
        private const Card.Cards AmaniBerserker = Card.Cards.EX1_393;         // [2 mana][2/3] Amani Berserker 
        private const Card.Cards Armorsmith = Card.Cards.EX1_402;         // [2 mana][1/4] Armorsmith 
        private const Card.Cards PatientAssassin = Card.Cards.EX1_522;        // [2 mana][1/1] Patient Assassin 
        private const Card.Cards ScavengingHyena = Card.Cards.EX1_531;        // [2 mana][2/2] Scavenging Hyena 
        private const Card.Cards NatPagle = Card.Cards.EX1_557;           // [2 mana][0/4] Nat Pagle 
        private const Card.Cards CruelTaskmaster = Card.Cards.EX1_603;        // [2 mana][2/2] Cruel Taskmaster 
        private const Card.Cards SorcerersApprentice = Card.Cards.EX1_608;        // [2 mana][3/2] Sorcerer's Apprentice 
        private const Card.Cards ManaWraith = Card.Cards.EX1_616;         // [2 mana][2/2] Mana Wraith 
        private const Card.Cards BloodsailRaider = Card.Cards.NEW1_018;       // [2 mana][2/3] Bloodsail Raider 
        private const Card.Cards KnifeJuggler = Card.Cards.NEW1_019;      // [2 mana][3/2] Knife Juggler 
        private const Card.Cards WildPyromancer = Card.Cards.NEW1_020;    // [2 mana][3/2] Wild Pyromancer 
        private const Card.Cards Doomsayer = Card.Cards.NEW1_021;     // [2 mana][0/7] Doomsayer 
        private const Card.Cards FaerieDragon = Card.Cards.NEW1_023;      // [2 mana][3/2] Faerie Dragon 
        private const Card.Cards MillhouseManastorm = Card.Cards.NEW1_029;    // [2 mana][4/4] Millhouse Manastorm 
        private const Card.Cards MasterSwordsmith = Card.Cards.NEW1_037;      // [2 mana][1/3] Master Swordsmith 
        private const Card.Cards MuseumCurator = Card.Cards.LOE_006;          // [2 mana][1/2] Museum Curator 
        private const Card.Cards DarkPeddler = Card.Cards.LOE_023;        // [2 mana][2/2] Dark Peddler 
        private const Card.Cards JeweledScarab = Card.Cards.LOE_029;          // [2 mana][1/1] Jeweled Scarab 
        private const Card.Cards HugeToad = Card.Cards.LOE_046;           // [2 mana][3/2] Huge Toad 
        private const Card.Cards CaptainsParrot = Card.Cards.NEW1_016;    // [2 mana][1/1] Captain's Parrot 
        private const Card.Cards HauntedCreeper = Card.Cards.FP1_002;         // [2 mana][1/2] Haunted Creeper 
        private const Card.Cards EchoingOoze = Card.Cards.FP1_003;        // [2 mana][1/2] Echoing Ooze 
        private const Card.Cards MadScientist = Card.Cards.FP1_004;           // [2 mana][2/2] Mad Scientist 
        private const Card.Cards NerubianEgg = Card.Cards.FP1_007;        // [2 mana][0/2] Nerubian Egg 
        private const Card.Cards NerubarWeblord = Card.Cards.FP1_017;         // [2 mana][1/4] Nerub'ar Weblord 
        private const Card.Cards UnstableGhoul = Card.Cards.FP1_024;          // [2 mana][1/3] Unstable Ghoul 
        private const Card.Cards Snowchugger = Card.Cards.GVG_002;        // [2 mana][2/3] Snowchugger 
        private const Card.Cards Mechwarper = Card.Cards.GVG_006;         // [2 mana][2/3] Mechwarper 
        private const Card.Cards Shrinkmeister = Card.Cards.GVG_011;          // [2 mana][3/2] Shrinkmeister 
        private const Card.Cards MistressofPain = Card.Cards.GVG_018;         // [2 mana][1/4] Mistress of Pain 
        private const Card.Cards GoblinAutoBarber = Card.Cards.GVG_023;           // [2 mana][3/2] Goblin Auto-Barber 
        private const Card.Cards OneeyedCheat = Card.Cards.GVG_025;           // [2 mana][4/1] One-eyed Cheat 
        private const Card.Cards AnodizedRoboCub = Card.Cards.GVG_030;        // [2 mana][2/2] Anodized Robo Cub 
        private const Card.Cards WhirlingZapomatic = Card.Cards.GVG_037;          // [2 mana][3/2] Whirling Zap-o-matic 
        private const Card.Cards VitalityTotem = Card.Cards.GVG_039;          // [2 mana][0/3] Vitality Totem 
        private const Card.Cards Glaivezooka = Card.Cards.GVG_043;        // [2 mana][2/2] Glaivezooka 
        private const Card.Cards ShieldedMinibot = Card.Cards.GVG_058;        // [2 mana][2/2] Shielded Minibot 
        private const Card.Cards Puddlestomper = Card.Cards.GVG_064;          // [2 mana][3/2] Puddlestomper 
        private const Card.Cards StonesplinterTrogg = Card.Cards.GVG_067;         // [2 mana][2/3] Stonesplinter Trogg 
        private const Card.Cards Shadowboxer = Card.Cards.GVG_072;        // [2 mana][2/3] Shadowboxer 
        private const Card.Cards ShipsCannon = Card.Cards.GVG_075;        // [2 mana][2/3] Ship's Cannon 
        private const Card.Cards ExplosiveSheep = Card.Cards.GVG_076;         // [2 mana][1/1] Explosive Sheep 
        private const Card.Cards GilblinStalker = Card.Cards.GVG_081;         // [2 mana][2/3] Gilblin Stalker 
        private const Card.Cards AnnoyoTron = Card.Cards.GVG_085;         // [2 mana][1/2] Annoy-o-Tron 
        private const Card.Cards SteamwheedleSniper = Card.Cards.GVG_087;         // [2 mana][2/3] Steamwheedle Sniper 
        private const Card.Cards MicroMachine = Card.Cards.GVG_103;           // [2 mana][1/2] Micro Machine 
        private const Card.Cards Recombobulator = Card.Cards.GVG_108;         // [2 mana][3/2] Recombobulator 
        private const Card.Cards FallenHero = Card.Cards.AT_003;          // [2 mana][3/2] Fallen Hero 
        private const Card.Cards TinyKnightofEvil = Card.Cards.AT_021;        // [2 mana][3/2] Tiny Knight of Evil 
        private const Card.Cards Wrathguard = Card.Cards.AT_026;          // [2 mana][4/3] Wrathguard 
        private const Card.Cards UndercityValiant = Card.Cards.AT_030;        // [2 mana][3/2] Undercity Valiant 
        private const Card.Cards Cutpurse = Card.Cards.AT_031;        // [2 mana][2/2] Cutpurse 
        private const Card.Cards DarnassusAspirant = Card.Cards.AT_038;           // [2 mana][2/3] Darnassus Aspirant 
        private const Card.Cards DruidoftheSaber = Card.Cards.AT_042;         // [2 mana][2/1] Druid of the Saber 
        private const Card.Cards TotemGolem = Card.Cards.AT_052;          // [2 mana][3/4] Totem Golem 
        private const Card.Cards KingsElekk = Card.Cards.AT_058;          // [2 mana][3/2] King's Elekk 
        private const Card.Cards SparringPartner = Card.Cards.AT_069;         // [2 mana][3/2] Sparring Partner 
        private const Card.Cards AlexstraszasChampion = Card.Cards.AT_071;        // [2 mana][2/3] Alexstrasza's Champion 
        private const Card.Cards ArgentLance = Card.Cards.AT_077;         // [2 mana][2/2] Argent Lance 
        private const Card.Cards GarrisonCommander = Card.Cards.AT_080;           // [2 mana][2/3] Garrison Commander 
        private const Card.Cards LanceCarrier = Card.Cards.AT_084;        // [2 mana][1/2] Lance Carrier 
        private const Card.Cards BoneguardLieutenant = Card.Cards.AT_089;         // [2 mana][3/2] Boneguard Lieutenant 
        private const Card.Cards FlameJuggler = Card.Cards.AT_094;        // [2 mana][2/3] Flame Juggler 
        private const Card.Cards ArgentWatchman = Card.Cards.AT_109;          // [2 mana][2/4] Argent Watchman 
        private const Card.Cards WyrmrestAgent = Card.Cards.AT_116;           // [2 mana][1/4] Wyrmrest Agent 
        private const Card.Cards MarkoftheWild = Card.Cards.CS2_009;          // [2 mana][0/0] Mark of the Wild 
        private const Card.Cards WildGrowth = Card.Cards.CS2_013;         // [2 mana][0/0] Wild Growth 
        private const Card.Cards Frostbolt = Card.Cards.CS2_024;          // [2 mana][0/0] Frostbolt 
        private const Card.Cards ArcaneExplosion = Card.Cards.CS2_025;        // [2 mana][0/0] Arcane Explosion 
        private const Card.Cards Windfury = Card.Cards.CS2_039;           // [2 mana][0/0] Windfury 
        private const Card.Cards HolyLight = Card.Cards.CS2_089;          // [2 mana][0/0] Holy Light 
        private const Card.Cards HeroicStrike = Card.Cards.CS2_105;           // [2 mana][0/0] Heroic Strike 
        private const Card.Cards Cleave = Card.Cards.CS2_114;         // [2 mana][0/0] Cleave 
        private const Card.Cards ShadowWordPain = Card.Cards.CS2_234;         // [2 mana][0/0] Shadow Word: Pain 
        private const Card.Cards DivineSpirit = Card.Cards.CS2_236;           // [2 mana][0/0] Divine Spirit 
        private const Card.Cards MindBlast = Card.Cards.DS1_233;          // [2 mana][0/0] Mind Blast 
        private const Card.Cards Shiv = Card.Cards.EX1_278;           // [2 mana][0/0] Shiv 
        private const Card.Cards Sap = Card.Cards.EX1_581;        // [2 mana][0/0] Sap 
        private const Card.Cards AncestralSpirit = Card.Cards.CS2_038;        // [2 mana][0/0] Ancestral Spirit 
        private const Card.Cards Rampage = Card.Cards.CS2_104;        // [2 mana][0/0] Rampage 
        private const Card.Cards BladeFlurry = Card.Cards.CS2_233;        // [2 mana][0/0] Blade Flurry 
        private const Card.Cards Eviscerate = Card.Cards.EX1_124;         // [2 mana][0/0] Eviscerate 
        private const Card.Cards Betrayal = Card.Cards.EX1_126;           // [2 mana][0/0] Betrayal 
        private const Card.Cards Wrath = Card.Cards.EX1_154;          // [2 mana][0/0] Wrath 
        private const Card.Cards PoweroftheWild = Card.Cards.EX1_160;         // [2 mana][0/0] Power of the Wild 
        private const Card.Cards Slam = Card.Cards.EX1_391;           // [2 mana][0/0] Slam 
        private const Card.Cards BattleRage = Card.Cards.EX1_392;         // [2 mana][0/0] Battle Rage 
        private const Card.Cards Misdirection = Card.Cards.EX1_533;           // [2 mana][0/0] Misdirection 
        private const Card.Cards Flare = Card.Cards.EX1_544;          // [2 mana][0/0] Flare 
        private const Card.Cards SnakeTrap = Card.Cards.EX1_554;          // [2 mana][0/0] Snake Trap 
        private const Card.Cards Demonfire = Card.Cards.EX1_596;          // [2 mana][0/0] Demonfire 
        private const Card.Cards Snipe = Card.Cards.EX1_609;          // [2 mana][0/0] Snipe 
        private const Card.Cards ExplosiveTrap = Card.Cards.EX1_610;          // [2 mana][0/0] Explosive Trap 
        private const Card.Cards FreezingTrap = Card.Cards.EX1_611;           // [2 mana][0/0] Freezing Trap 
        private const Card.Cards Equality = Card.Cards.EX1_619;           // [2 mana][0/0] Equality 
        private const Card.Cards CommandingShout = Card.Cards.NEW1_036;       // [2 mana][0/0] Commanding Shout 
        private const Card.Cards CurseofRafaam = Card.Cards.LOE_007;          // [2 mana][0/0] Curse of Rafaam 
        private const Card.Cards DartTrap = Card.Cards.LOE_021;           // [2 mana][0/0] Dart Trap 
        private const Card.Cards ExplorersHat = Card.Cards.LOE_105;           // [2 mana][0/0] Explorer's Hat 
        private const Card.Cards Reincarnate = Card.Cards.FP1_025;        // [2 mana][0/0] Reincarnate 
        private const Card.Cards Flamecannon = Card.Cards.GVG_001;        // [2 mana][0/0] Flamecannon 
        private const Card.Cards UnstablePortal = Card.Cards.GVG_003;         // [2 mana][0/0] Unstable Portal 
        private const Card.Cards Darkbomb = Card.Cards.GVG_015;           // [2 mana][0/0] Darkbomb 
        private const Card.Cards CallPet = Card.Cards.GVG_017;        // [2 mana][0/0] Call Pet 
        private const Card.Cards FeignDeath = Card.Cards.GVG_026;         // [2 mana][0/0] Feign Death 
        private const Card.Cards Crackle = Card.Cards.GVG_038;        // [2 mana][0/0] Crackle 
        private const Card.Cards SealofLight = Card.Cards.GVG_057;        // [2 mana][0/0] Seal of Light 
        private const Card.Cards GangUp = Card.Cards.BRM_007;         // [2 mana][0/0] Gang Up 
        private const Card.Cards LavaShock = Card.Cards.BRM_011;          // [2 mana][0/0] Lava Shock 
        private const Card.Cards QuickShot = Card.Cards.BRM_013;          // [2 mana][0/0] Quick Shot 
        private const Card.Cards Revenge = Card.Cards.BRM_015;        // [2 mana][0/0] Revenge 
        private const Card.Cards Resurrect = Card.Cards.BRM_017;          // [2 mana][0/0] Resurrect 
        private const Card.Cards Convert = Card.Cards.AT_015;         // [2 mana][0/0] Convert 
        private const Card.Cards Confuse = Card.Cards.AT_016;         // [2 mana][0/0] Confuse 
        private const Card.Cards Demonfuse = Card.Cards.AT_024;           // [2 mana][0/0] Demonfuse 
        private const Card.Cards AncestralKnowledge = Card.Cards.AT_053;          // [2 mana][0/0] Ancestral Knowledge 
        private const Card.Cards BearTrap = Card.Cards.AT_060;        // [2 mana][0/0] Bear Trap 
        private const Card.Cards LockandLoad = Card.Cards.AT_061;         // [2 mana][0/0] Lock and Load 
        private const Card.Cards Bolster = Card.Cards.AT_068;         // [2 mana][0/0] Bolster 
        private const Card.Cards MagmaRager = Card.Cards.CS2_118;         // [3 mana][5/1] Magma Rager 
        private const Card.Cards RaidLeader = Card.Cards.CS2_122;         // [3 mana][2/2] Raid Leader 
        private const Card.Cards Wolfrider = Card.Cards.CS2_124;          // [3 mana][3/1] Wolfrider 
        private const Card.Cards IronfurGrizzly = Card.Cards.CS2_125;         // [3 mana][3/3] Ironfur Grizzly 
        private const Card.Cards SilverbackPatriarch = Card.Cards.CS2_127;        // [3 mana][1/4] Silverback Patriarch 
        private const Card.Cards IronforgeRifleman = Card.Cards.CS2_141;          // [3 mana][2/2] Ironforge Rifleman 
        private const Card.Cards RazorfenHunter = Card.Cards.CS2_196;         // [3 mana][2/3] Razorfen Hunter 
        private const Card.Cards ShatteredSunCleric = Card.Cards.EX1_019;         // [3 mana][3/2] Shattered Sun Cleric 
        private const Card.Cards WarsongCommander = Card.Cards.EX1_084;           // [3 mana][2/3] Warsong Commander 
        private const Card.Cards DalaranMage = Card.Cards.EX1_582;        // [3 mana][1/4] Dalaran Mage 
        private const Card.Cards EarthenRingFarseer = Card.Cards.CS2_117;         // [3 mana][3/3] Earthen Ring Farseer 
        private const Card.Cards InjuredBlademaster = Card.Cards.CS2_181;         // [3 mana][4/7] Injured Blademaster 
        private const Card.Cards BigGameHunter = Card.Cards.EX1_005;          // [3 mana][4/2] Big Game Hunter 
        private const Card.Cards AlarmoBot = Card.Cards.EX1_006;          // [3 mana][0/3] Alarm-o-Bot 
        private const Card.Cards AcolyteofPain = Card.Cards.EX1_007;          // [3 mana][1/3] Acolyte of Pain 
        private const Card.Cards KingMukla = Card.Cards.EX1_014;          // [3 mana][5/5] King Mukla 
        private const Card.Cards JunglePanther = Card.Cards.EX1_017;          // [3 mana][4/2] Jungle Panther 
        private const Card.Cards ScarletCrusader = Card.Cards.EX1_020;        // [3 mana][3/1] Scarlet Crusader 
        private const Card.Cards ThrallmarFarseer = Card.Cards.EX1_021;           // [3 mana][2/3] Thrallmar Farseer 
        private const Card.Cards QuestingAdventurer = Card.Cards.EX1_044;         // [3 mana][2/2] Questing Adventurer 
        private const Card.Cards ColdlightOracle = Card.Cards.EX1_050;        // [3 mana][2/2] Coldlight Oracle 
        private const Card.Cards TinkmasterOverspark = Card.Cards.EX1_083;        // [3 mana][3/3] Tinkmaster Overspark 
        private const Card.Cards MindControlTech = Card.Cards.EX1_085;        // [3 mana][3/3] Mind Control Tech 
        private const Card.Cards ArcaneGolem = Card.Cards.EX1_089;        // [3 mana][4/2] Arcane Golem 
        private const Card.Cards Demolisher = Card.Cards.EX1_102;         // [3 mana][1/4] Demolisher 
        private const Card.Cards ColdlightSeer = Card.Cards.EX1_103;          // [3 mana][2/3] Coldlight Seer 
        private const Card.Cards PerditionsBlade = Card.Cards.EX1_133;        // [3 mana][2/2] Perdition's Blade 
        private const Card.Cards SI7Agent = Card.Cards.EX1_134;           // [3 mana][3/3] SI:7 Agent 
        private const Card.Cards EmperorCobra = Card.Cards.EX1_170;           // [3 mana][2/3] Emperor Cobra 
        private const Card.Cards UnboundElemental = Card.Cards.EX1_258;           // [3 mana][2/4] Unbound Elemental 
        private const Card.Cards Felguard = Card.Cards.EX1_301;           // [3 mana][3/5] Felguard 
        private const Card.Cards VoidTerror = Card.Cards.EX1_304;         // [3 mana][3/3] Void Terror 
        private const Card.Cards SwordofJustice = Card.Cards.EX1_366;         // [3 mana][1/5] Sword of Justice 
        private const Card.Cards AldorPeacekeeper = Card.Cards.EX1_382;           // [3 mana][3/3] Aldor Peacekeeper 
        private const Card.Cards TaurenWarrior = Card.Cards.EX1_390;          // [3 mana][2/3] Tauren Warrior 
        private const Card.Cards RagingWorgen = Card.Cards.EX1_412;           // [3 mana][3/3] Raging Worgen 
        private const Card.Cards MurlocWarleader = Card.Cards.EX1_507;        // [3 mana][3/3] Murloc Warleader 
        private const Card.Cards EaglehornBow = Card.Cards.EX1_536;           // [3 mana][3/2] Eaglehorn Bow 
        private const Card.Cards HarvestGolem = Card.Cards.EX1_556;           // [3 mana][2/3] Harvest Golem 
        private const Card.Cards ManaTideTotem = Card.Cards.EX1_575;          // [3 mana][0/3] Mana Tide Totem 
        private const Card.Cards BloodKnight = Card.Cards.EX1_590;        // [3 mana][3/3] Blood Knight 
        private const Card.Cards ImpMaster = Card.Cards.EX1_597;          // [3 mana][1/5] Imp Master 
        private const Card.Cards FrothingBerserker = Card.Cards.EX1_604;          // [3 mana][2/4] Frothing Berserker 
        private const Card.Cards KirinTorMage = Card.Cards.EX1_612;           // [3 mana][4/3] Kirin Tor Mage 
        private const Card.Cards EdwinVanCleef = Card.Cards.EX1_613;          // [3 mana][2/2] Edwin VanCleef 
        private const Card.Cards SouthseaCaptain = Card.Cards.NEW1_027;       // [3 mana][3/3] Southsea Captain 
        private const Card.Cards FlesheatingGhoul = Card.Cards.tt_004;        // [3 mana][2/3] Flesheating Ghoul 
        private const Card.Cards UnearthedRaptor = Card.Cards.LOE_019;        // [3 mana][3/4] Unearthed Raptor 
        private const Card.Cards DesertCamel = Card.Cards.LOE_020;        // [3 mana][2/4] Desert Camel 
        private const Card.Cards FierceMonkey = Card.Cards.LOE_022;           // [3 mana][3/4] Fierce Monkey 
        private const Card.Cards MountedRaptor = Card.Cards.LOE_050;          // [3 mana][3/2] Mounted Raptor 
        private const Card.Cards BrannBronzebeard = Card.Cards.LOE_077;           // [3 mana][2/4] Brann Bronzebeard 
        private const Card.Cards ShadeofNaxxramas = Card.Cards.FP1_005;           // [3 mana][2/2] Shade of Naxxramas 
        private const Card.Cards Deathlord = Card.Cards.FP1_009;          // [3 mana][2/8] Deathlord 
        private const Card.Cards DarkCultist = Card.Cards.FP1_023;        // [3 mana][3/4] Dark Cultist 
        private const Card.Cards StoneskinGargoyle = Card.Cards.FP1_027;          // [3 mana][1/4] Stoneskin Gargoyle 
        private const Card.Cards DancingSwords = Card.Cards.FP1_029;          // [3 mana][4/4] Dancing Swords 
        private const Card.Cards CogmastersWrench = Card.Cards.GVG_024;           // [3 mana][1/3] Cogmaster's Wrench 
        private const Card.Cards IronSensei = Card.Cards.GVG_027;         // [3 mana][2/2] Iron Sensei 
        private const Card.Cards GroveTender = Card.Cards.GVG_032;        // [3 mana][2/4] Grove Tender 
        private const Card.Cards Powermace = Card.Cards.GVG_036;          // [3 mana][3/2] Powermace 
        private const Card.Cards SpiderTank = Card.Cards.GVG_044;         // [3 mana][3/4] Spider Tank 
        private const Card.Cards MetaltoothLeaper = Card.Cards.GVG_048;           // [3 mana][3/3] Metaltooth Leaper 
        private const Card.Cards OgreWarmaul = Card.Cards.GVG_054;        // [3 mana][4/2] Ogre Warmaul 
        private const Card.Cards Coghammer = Card.Cards.GVG_059;          // [3 mana][2/3] Coghammer 
        private const Card.Cards OgreBrute = Card.Cards.GVG_065;          // [3 mana][4/4] Ogre Brute 
        private const Card.Cards FlyingMachine = Card.Cards.GVG_084;          // [3 mana][1/4] Flying Machine 
        private const Card.Cards Illuminator = Card.Cards.GVG_089;        // [3 mana][2/4] Illuminator 
        private const Card.Cards GnomishExperimenter = Card.Cards.GVG_092;        // [3 mana][3/2] Gnomish Experimenter 
        private const Card.Cards GoblinSapper = Card.Cards.GVG_095;           // [3 mana][2/4] Goblin Sapper 
        private const Card.Cards LilExorcist = Card.Cards.GVG_097;        // [3 mana][2/3] Lil' Exorcist 
        private const Card.Cards GnomereganInfantry = Card.Cards.GVG_098;         // [3 mana][1/4] Gnomeregan Infantry 
        private const Card.Cards ScarletPurifier = Card.Cards.GVG_101;        // [3 mana][4/3] Scarlet Purifier 
        private const Card.Cards TinkertownTechnician = Card.Cards.GVG_102;           // [3 mana][3/3] Tinkertown Technician 
        private const Card.Cards Hobgoblin = Card.Cards.GVG_104;          // [3 mana][2/3] Hobgoblin 
        private const Card.Cards SootSpewer = Card.Cards.GVG_123;         // [3 mana][3/3] Soot Spewer 
        private const Card.Cards Flamewaker = Card.Cards.BRM_002;         // [3 mana][2/4] Flamewaker 
        private const Card.Cards ImpGangBoss = Card.Cards.BRM_006;        // [3 mana][2/4] Imp Gang Boss 
        private const Card.Cards DruidoftheFlame = Card.Cards.BRM_010;        // [3 mana][2/2] Druid of the Flame 
        private const Card.Cards BlackwingTechnician = Card.Cards.BRM_033;        // [3 mana][2/4] Blackwing Technician 
        private const Card.Cards Spellslinger = Card.Cards.AT_007;        // [3 mana][3/4] Spellslinger 
        private const Card.Cards Shadowfiend = Card.Cards.AT_014;         // [3 mana][3/3] Shadowfiend 
        private const Card.Cards ShadyDealer = Card.Cards.AT_032;         // [3 mana][4/3] Shady Dealer 
        private const Card.Cards TuskarrTotemic = Card.Cards.AT_046;          // [3 mana][3/2] Tuskarr Totemic 
        private const Card.Cards Stablemaster = Card.Cards.AT_057;        // [3 mana][4/2] Stablemaster 
        private const Card.Cards Dreadscale = Card.Cards.AT_063t;         // [3 mana][4/2] Dreadscale 
        private const Card.Cards KingsDefender = Card.Cards.AT_065;           // [3 mana][3/2] King's Defender 
        private const Card.Cards OrgrimmarAspirant = Card.Cards.AT_066;           // [3 mana][3/3] Orgrimmar Aspirant 
        private const Card.Cards WarhorseTrainer = Card.Cards.AT_075;         // [3 mana][2/4] Warhorse Trainer 
        private const Card.Cards DragonhawkRider = Card.Cards.AT_083;         // [3 mana][3/3] Dragonhawk Rider 
        private const Card.Cards Saboteur = Card.Cards.AT_086;        // [3 mana][4/3] Saboteur 
        private const Card.Cards ArgentHorserider = Card.Cards.AT_087;        // [3 mana][2/1] Argent Horserider 
        private const Card.Cards IceRager = Card.Cards.AT_092;        // [3 mana][5/2] Ice Rager 
        private const Card.Cards SilentKnight = Card.Cards.AT_095;        // [3 mana][2/2] Silent Knight 
        private const Card.Cards SilverHandRegent = Card.Cards.AT_100;        // [3 mana][3/3] Silver Hand Regent 
        private const Card.Cards LightsChampion = Card.Cards.AT_106;          // [3 mana][4/3] Light's Champion 
        private const Card.Cards ColiseumManager = Card.Cards.AT_110;         // [3 mana][2/5] Coliseum Manager 
        private const Card.Cards FencingCoach = Card.Cards.AT_115;        // [3 mana][2/2] Fencing Coach 
        private const Card.Cards MasterofCeremonies = Card.Cards.AT_117;          // [3 mana][4/2] Master of Ceremonies 
        private const Card.Cards FjolaLightbane = Card.Cards.AT_129;          // [3 mana][3/4] Fjola Lightbane 
        private const Card.Cards EydisDarkbane = Card.Cards.AT_131;           // [3 mana][3/4] Eydis Darkbane 
        private const Card.Cards HealingTouch = Card.Cards.CS2_007;           // [3 mana][0/0] Healing Touch 
        private const Card.Cards SavageRoar = Card.Cards.CS2_011;         // [3 mana][0/0] Savage Roar 
        private const Card.Cards ArcaneIntellect = Card.Cards.CS2_023;        // [3 mana][0/0] Arcane Intellect 
        private const Card.Cards FrostNova = Card.Cards.CS2_026;          // [3 mana][0/0] Frost Nova 
        private const Card.Cards ShadowBolt = Card.Cards.CS2_057;         // [3 mana][0/0] Shadow Bolt 
        private const Card.Cards DrainLife = Card.Cards.CS2_061;          // [3 mana][0/0] Drain Life 
        private const Card.Cards Charge = Card.Cards.CS2_103;         // [3 mana][0/0] Charge 
        private const Card.Cards FanofKnives = Card.Cards.EX1_129;        // [3 mana][0/0] Fan of Knives 
        private const Card.Cards Hex = Card.Cards.EX1_246;        // [3 mana][0/0] Hex 
        private const Card.Cards KillCommand = Card.Cards.EX1_539;        // [3 mana][0/0] Kill Command 
        private const Card.Cards ShieldBlock = Card.Cards.EX1_606;        // [3 mana][0/0] Shield Block 
        private const Card.Cards ShadowWordDeath = Card.Cards.EX1_622;        // [3 mana][0/0] Shadow Word: Death 
        private const Card.Cards AnimalCompanion = Card.Cards.NEW1_031;       // [3 mana][0/0] Animal Companion 
        private const Card.Cards FarSight = Card.Cards.CS2_053;           // [3 mana][0/0] Far Sight 
        private const Card.Cards Headcrack = Card.Cards.EX1_137;          // [3 mana][0/0] Headcrack 
        private const Card.Cards MarkofNature = Card.Cards.EX1_155;           // [3 mana][0/0] Mark of Nature 
        private const Card.Cards LavaBurst = Card.Cards.EX1_241;          // [3 mana][0/0] Lava Burst 
        private const Card.Cards FeralSpirit = Card.Cards.EX1_248;        // [3 mana][0/0] Feral Spirit 
        private const Card.Cards LightningStorm = Card.Cards.EX1_259;         // [3 mana][0/0] Lightning Storm 
        private const Card.Cards Counterspell = Card.Cards.EX1_287;           // [3 mana][0/0] Counterspell 
        private const Card.Cards IceBarrier = Card.Cards.EX1_289;         // [3 mana][0/0] Ice Barrier 
        private const Card.Cards MirrorEntity = Card.Cards.EX1_294;           // [3 mana][0/0] Mirror Entity 
        private const Card.Cards IceBlock = Card.Cards.EX1_295;           // [3 mana][0/0] Ice Block 
        private const Card.Cards SenseDemons = Card.Cards.EX1_317;        // [3 mana][0/0] Sense Demons 
        private const Card.Cards Thoughtsteal = Card.Cards.EX1_339;           // [3 mana][0/0] Thoughtsteal 
        private const Card.Cards DivineFavor = Card.Cards.EX1_349;        // [3 mana][0/0] Divine Favor 
        private const Card.Cards UnleashtheHounds = Card.Cards.EX1_538;           // [3 mana][0/0] Unleash the Hounds 
        private const Card.Cards Vaporize = Card.Cards.EX1_594;           // [3 mana][0/0] Vaporize 
        private const Card.Cards DeadlyShot = Card.Cards.EX1_617;         // [3 mana][0/0] Deadly Shot 
        private const Card.Cards Shadowform = Card.Cards.EX1_625;         // [3 mana][0/0] Shadowform 
        private const Card.Cards Spellbender = Card.Cards.tt_010;         // [3 mana][0/0] Spellbender 
        private const Card.Cards ForgottenTorch = Card.Cards.LOE_002;         // [3 mana][0/0] Forgotten Torch 
        private const Card.Cards Duplicate = Card.Cards.FP1_018;          // [3 mana][0/0] Duplicate 
        private const Card.Cards VelensChosen = Card.Cards.GVG_010;           // [3 mana][0/0] Velen's Chosen 
        private const Card.Cards BouncingBlade = Card.Cards.GVG_050;          // [3 mana][0/0] Bouncing Blade 
        private const Card.Cards MusterforBattle = Card.Cards.GVG_061;        // [3 mana][0/0] Muster for Battle 
        private const Card.Cards Demonwrath = Card.Cards.BRM_005;         // [3 mana][0/0] Demonwrath 
        private const Card.Cards Effigy = Card.Cards.AT_002;          // [3 mana][0/0] Effigy 
        private const Card.Cards PolymorphBoar = Card.Cards.AT_005;           // [3 mana][0/0] Polymorph: Boar 
        private const Card.Cards Burgle = Card.Cards.AT_033;          // [3 mana][0/0] Burgle 
        private const Card.Cards BeneaththeGrounds = Card.Cards.AT_035;           // [3 mana][0/0] Beneath the Grounds 
        private const Card.Cards Mulch = Card.Cards.AT_044;           // [3 mana][0/0] Mulch 
        private const Card.Cards HealingWave = Card.Cards.AT_048;         // [3 mana][0/0] Healing Wave 
        private const Card.Cards ElementalDestruction = Card.Cards.AT_051;        // [3 mana][0/0] Elemental Destruction 
        private const Card.Cards Powershot = Card.Cards.AT_056;           // [3 mana][0/0] Powershot 
        private const Card.Cards Bash = Card.Cards.AT_064;        // [3 mana][0/0] Bash 
        private const Card.Cards SealofChampions = Card.Cards.AT_074;         // [3 mana][0/0] Seal of Champions 
        private const Card.Cards WaterElemental = Card.Cards.CS2_033;         // [4 mana][3/6] Water Elemental 
        private const Card.Cards TruesilverChampion = Card.Cards.CS2_097;         // [4 mana][4/2] Truesilver Champion 
        private const Card.Cards OasisSnapjaw = Card.Cards.CS2_119;           // [4 mana][2/7] Oasis Snapjaw 
        private const Card.Cards StormwindKnight = Card.Cards.CS2_131;        // [4 mana][2/5] Stormwind Knight 
        private const Card.Cards GnomishInventor = Card.Cards.CS2_147;        // [4 mana][2/4] Gnomish Inventor 
        private const Card.Cards SenjinShieldmasta = Card.Cards.CS2_179;          // [4 mana][3/5] Sen'jin Shieldmasta 
        private const Card.Cards ChillwindYeti = Card.Cards.CS2_182;          // [4 mana][4/5] Chillwind Yeti 
        private const Card.Cards OgreMagi = Card.Cards.CS2_197;           // [4 mana][4/4] Ogre Magi 
        private const Card.Cards Houndmaster = Card.Cards.DS1_070;        // [4 mana][4/3] Houndmaster 
        private const Card.Cards DragonlingMechanic = Card.Cards.EX1_025;         // [4 mana][2/4] Dragonling Mechanic 
        private const Card.Cards Windspeaker = Card.Cards.EX1_587;        // [4 mana][3/3] Windspeaker 
        private const Card.Cards KorkronElite = Card.Cards.NEW1_011;      // [4 mana][4/3] Kor'kron Elite 
        private const Card.Cards SilvermoonGuardian = Card.Cards.EX1_023;         // [4 mana][3/3] Silvermoon Guardian 
        private const Card.Cards TwilightDrake = Card.Cards.EX1_043;          // [4 mana][4/1] Twilight Drake 
        private const Card.Cards DarkIronDwarf = Card.Cards.EX1_046;          // [4 mana][4/4] Dark Iron Dwarf 
        private const Card.Cards Spellbreaker = Card.Cards.EX1_048;           // [4 mana][4/3] Spellbreaker 
        private const Card.Cards AncientBrewmaster = Card.Cards.EX1_057;          // [4 mana][5/4] Ancient Brewmaster 
        private const Card.Cards DefenderofArgus = Card.Cards.EX1_093;        // [4 mana][2/3] Defender of Argus 
        private const Card.Cards KeeperoftheGrove = Card.Cards.EX1_166;           // [4 mana][2/4] Keeper of the Grove 
        private const Card.Cards EtherealArcanist = Card.Cards.EX1_274;           // [4 mana][3/3] Ethereal Arcanist 
        private const Card.Cards PitLord = Card.Cards.EX1_313;        // [4 mana][5/6] Pit Lord 
        private const Card.Cards SummoningPortal = Card.Cards.EX1_315;        // [4 mana][0/4] Summoning Portal 
        private const Card.Cards Lightspawn = Card.Cards.EX1_335;         // [4 mana][0/5] Lightspawn 
        private const Card.Cards MogushanWarden = Card.Cards.EX1_396;         // [4 mana][1/7] Mogu'shan Warden 
        private const Card.Cards ArathiWeaponsmith = Card.Cards.EX1_398;          // [4 mana][3/3] Arathi Weaponsmith 
        private const Card.Cards AncientMage = Card.Cards.EX1_584;        // [4 mana][2/5] Ancient Mage 
        private const Card.Cards AuchenaiSoulpriest = Card.Cards.EX1_591;         // [4 mana][3/5] Auchenai Soulpriest 
        private const Card.Cards CultMaster = Card.Cards.EX1_595;         // [4 mana][4/2] Cult Master 
        private const Card.Cards MasterofDisguise = Card.Cards.NEW1_014;      // [4 mana][4/4] Master of Disguise 
        private const Card.Cards DreadCorsair = Card.Cards.NEW1_022;      // [4 mana][3/3] Dread Corsair 
        private const Card.Cards VioletTeacher = Card.Cards.NEW1_026;     // [4 mana][3/5] Violet Teacher 
        private const Card.Cards TombPillager = Card.Cards.LOE_012;           // [4 mana][5/4] Tomb Pillager 
        private const Card.Cards RumblingElemental = Card.Cards.LOE_016;          // [4 mana][2/6] Rumbling Elemental 
        private const Card.Cards KeeperofUldaman = Card.Cards.LOE_017;        // [4 mana][3/4] Keeper of Uldaman 
        private const Card.Cards GorillabotA3 = Card.Cards.LOE_039;           // [4 mana][3/4] Gorillabot A-3 
        private const Card.Cards TombSpider = Card.Cards.LOE_047;         // [4 mana][3/3] Tomb Spider 
        private const Card.Cards JungleMoonkin = Card.Cards.LOE_051;          // [4 mana][4/4] Jungle Moonkin 
        private const Card.Cards EliseStarseeker = Card.Cards.LOE_079;        // [4 mana][3/5] Elise Starseeker 
        private const Card.Cards EerieStatue = Card.Cards.LOE_107;        // [4 mana][7/7] Eerie Statue 
        private const Card.Cards AncientShade = Card.Cards.LOE_110;           // [4 mana][7/4] Ancient Shade 
        private const Card.Cards AnimatedArmor = Card.Cards.LOE_119;          // [4 mana][4/4] Animated Armor 
        private const Card.Cards OldMurkEye = Card.Cards.EX1_062;         // [4 mana][2/4] Old Murk-Eye 
        private const Card.Cards WailingSoul = Card.Cards.FP1_016;        // [4 mana][3/5] Wailing Soul 
        private const Card.Cards DeathsBite = Card.Cards.FP1_021;         // [4 mana][4/2] Death's Bite 
        private const Card.Cards Voidcaller = Card.Cards.FP1_022;         // [4 mana][3/4] Voidcaller 
        private const Card.Cards AnubarAmbusher = Card.Cards.FP1_026;         // [4 mana][5/5] Anub'ar Ambusher 
        private const Card.Cards BaronRivendare = Card.Cards.FP1_031;         // [4 mana][1/7] Baron Rivendare 
        private const Card.Cards GoblinBlastmage = Card.Cards.GVG_004;        // [4 mana][5/4] Goblin Blastmage 
        private const Card.Cards FelCannon = Card.Cards.GVG_020;          // [4 mana][3/5] Fel Cannon 
        private const Card.Cards SiltfinSpiritwalker = Card.Cards.GVG_040;        // [4 mana][2/5] Siltfin Spiritwalker 
        private const Card.Cards ScrewjankClunker = Card.Cards.GVG_055;           // [4 mana][2/5] Screwjank Clunker 
        private const Card.Cards DunemaulShaman = Card.Cards.GVG_066;         // [4 mana][5/4] Dunemaul Shaman 
        private const Card.Cards BurlyRockjawTrogg = Card.Cards.GVG_068;          // [4 mana][3/5] Burly Rockjaw Trogg 
        private const Card.Cards LostTallstrider = Card.Cards.GVG_071;        // [4 mana][5/4] Lost Tallstrider 
        private const Card.Cards KezanMystic = Card.Cards.GVG_074;        // [4 mana][4/3] Kezan Mystic 
        private const Card.Cards MechanicalYeti = Card.Cards.GVG_078;         // [4 mana][4/5] Mechanical Yeti 
        private const Card.Cards ArcaneNullifierX21 = Card.Cards.GVG_091;         // [4 mana][2/5] Arcane Nullifier X-21 
        private const Card.Cards Jeeves = Card.Cards.GVG_094;         // [4 mana][1/4] Jeeves 
        private const Card.Cards PilotedShredder = Card.Cards.GVG_096;        // [4 mana][4/3] Piloted Shredder 
        private const Card.Cards EnhanceoMechano = Card.Cards.GVG_107;        // [4 mana][3/2] Enhance-o Mechano 
        private const Card.Cards MiniMage = Card.Cards.GVG_109;           // [4 mana][4/1] Mini-Mage 
        private const Card.Cards WeeSpellstopper = Card.Cards.GVG_122;        // [4 mana][2/5] Wee Spellstopper 
        private const Card.Cards FireguardDestroyer = Card.Cards.BRM_012;         // [4 mana][3/6] Fireguard Destroyer 
        private const Card.Cards CoreRager = Card.Cards.BRM_014;          // [4 mana][4/4] Core Rager 
        private const Card.Cards AxeFlinger = Card.Cards.BRM_016;         // [4 mana][2/5] Axe Flinger 
        private const Card.Cards DragonkinSorcerer = Card.Cards.BRM_020;          // [4 mana][3/5] Dragonkin Sorcerer 
        private const Card.Cards HungryDragon = Card.Cards.BRM_026;           // [4 mana][5/6] Hungry Dragon 
        private const Card.Cards DalaranAspirant = Card.Cards.AT_006;         // [4 mana][3/5] Dalaran Aspirant 
        private const Card.Cards HolyChampion = Card.Cards.AT_011;        // [4 mana][3/5] Holy Champion 
        private const Card.Cards SpawnofShadows = Card.Cards.AT_012;          // [4 mana][5/4] Spawn of Shadows 
        private const Card.Cards TwilightGuardian = Card.Cards.AT_017;        // [4 mana][2/6] Twilight Guardian 
        private const Card.Cards Dreadsteed = Card.Cards.AT_019;          // [4 mana][1/1] Dreadsteed 
        private const Card.Cards PoisonedBlade = Card.Cards.AT_034;           // [4 mana][1/3] Poisoned Blade 
        private const Card.Cards SavageCombatant = Card.Cards.AT_039;         // [4 mana][5/4] Savage Combatant 
        private const Card.Cards Wildwalker = Card.Cards.AT_040;          // [4 mana][4/4] Wildwalker 
        private const Card.Cards DraeneiTotemcarver = Card.Cards.AT_047;          // [4 mana][4/4] Draenei Totemcarver 
        private const Card.Cards ChargedHammer = Card.Cards.AT_050;           // [4 mana][2/4] Charged Hammer 
        private const Card.Cards MagnataurAlpha = Card.Cards.AT_067;          // [4 mana][5/3] Magnataur Alpha 
        private const Card.Cards MurlocKnight = Card.Cards.AT_076;        // [4 mana][3/4] Murloc Knight 
        private const Card.Cards MaidenoftheLake = Card.Cards.AT_085;         // [4 mana][2/6] Maiden of the Lake 
        private const Card.Cards TournamentMedic = Card.Cards.AT_091;         // [4 mana][1/8] Tournament Medic 
        private const Card.Cards FrigidSnobold = Card.Cards.AT_093;           // [4 mana][2/6] Frigid Snobold 
        private const Card.Cards ArmoredWarhorse = Card.Cards.AT_108;         // [4 mana][5/3] Armored Warhorse 
        private const Card.Cards RefreshmentVendor = Card.Cards.AT_111;           // [4 mana][3/5] Refreshment Vendor 
        private const Card.Cards EvilHeckler = Card.Cards.AT_114;         // [4 mana][5/4] Evil Heckler 
        private const Card.Cards CrowdFavorite = Card.Cards.AT_121;           // [4 mana][4/4] Crowd Favorite 
        private const Card.Cards GormoktheImpaler = Card.Cards.AT_122;        // [4 mana][4/4] Gormok the Impaler 
        private const Card.Cards Swipe = Card.Cards.CS2_012;          // [4 mana][0/0] Swipe 
        private const Card.Cards Polymorph = Card.Cards.CS2_022;          // [4 mana][0/0] Polymorph 
        private const Card.Cards Fireball = Card.Cards.CS2_029;           // [4 mana][0/0] Fireball 
        private const Card.Cards Hellfire = Card.Cards.CS2_062;           // [4 mana][0/0] Hellfire 
        private const Card.Cards BlessingofKings = Card.Cards.CS2_092;        // [4 mana][0/0] Blessing of Kings 
        private const Card.Cards Consecration = Card.Cards.CS2_093;           // [4 mana][0/0] Consecration 
        private const Card.Cards HammerofWrath = Card.Cards.CS2_094;          // [4 mana][0/0] Hammer of Wrath 
        private const Card.Cards MultiShot = Card.Cards.DS1_183;          // [4 mana][0/0] Multi-Shot 
        private const Card.Cards SouloftheForest = Card.Cards.EX1_158;        // [4 mana][0/0] Soul of the Forest 
        private const Card.Cards ConeofCold = Card.Cards.EX1_275;         // [4 mana][0/0] Cone of Cold 
        private const Card.Cards Shadowflame = Card.Cards.EX1_303;        // [4 mana][0/0] Shadowflame 
        private const Card.Cards ShadowMadness = Card.Cards.EX1_334;          // [4 mana][0/0] Shadow Madness 
        private const Card.Cards Mindgames = Card.Cards.EX1_345;          // [4 mana][0/0] Mindgames 
        private const Card.Cards MortalStrike = Card.Cards.EX1_408;           // [4 mana][0/0] Mortal Strike 
        private const Card.Cards Bite = Card.Cards.EX1_570;           // [4 mana][0/0] Bite 
        private const Card.Cards MassDispel = Card.Cards.EX1_626;         // [4 mana][0/0] Mass Dispel 
        private const Card.Cards PoisonSeeds = Card.Cards.FP1_019;        // [4 mana][0/0] Poison Seeds 
        private const Card.Cards EchoofMedivh = Card.Cards.GVG_005;           // [4 mana][0/0] Echo of Medivh 
        private const Card.Cards TinkersSharpswordOil = Card.Cards.GVG_022;           // [4 mana][0/0] Tinker's Sharpsword Oil 
        private const Card.Cards AncestorsCall = Card.Cards.GVG_029;          // [4 mana][0/0] Ancestor's Call 
        private const Card.Cards Implosion = Card.Cards.GVG_045;          // [4 mana][0/0] Imp-losion 
        private const Card.Cards Sabotage = Card.Cards.GVG_047;           // [4 mana][0/0] Sabotage 
        private const Card.Cards FistofJaraxxus = Card.Cards.AT_022;          // [4 mana][0/0] Fist of Jaraxxus 
        private const Card.Cards AstralCommunion = Card.Cards.AT_043;         // [4 mana][0/0] Astral Communion 
        private const Card.Cards AssassinsBlade = Card.Cards.CS2_080;         // [5 mana][3/4] Assassin's Blade 
        private const Card.Cards ArcaniteReaper = Card.Cards.CS2_112;         // [5 mana][5/2] Arcanite Reaper 
        private const Card.Cards StormpikeCommando = Card.Cards.CS2_150;          // [5 mana][4/2] Stormpike Commando 
        private const Card.Cards BootyBayBodyguard = Card.Cards.CS2_187;          // [5 mana][5/4] Booty Bay Bodyguard 
        private const Card.Cards FrostwolfWarlord = Card.Cards.CS2_226;           // [5 mana][4/4] Frostwolf Warlord 
        private const Card.Cards StarvingBuzzard = Card.Cards.CS2_237;        // [5 mana][3/2] Starving Buzzard 
        private const Card.Cards DarkscaleHealer = Card.Cards.DS1_055;        // [5 mana][4/5] Darkscale Healer 
        private const Card.Cards TundraRhino = Card.Cards.DS1_178;        // [5 mana][2/5] Tundra Rhino 
        private const Card.Cards GurubashiBerserker = Card.Cards.EX1_399;         // [5 mana][2/7] Gurubashi Berserker 
        private const Card.Cards Nightblade = Card.Cards.EX1_593;         // [5 mana][4/4] Nightblade 
        private const Card.Cards FenCreeper = Card.Cards.CS1_069;         // [5 mana][3/6] Fen Creeper 
        private const Card.Cards SilverHandKnight = Card.Cards.CS2_151;           // [5 mana][4/4] Silver Hand Knight 
        private const Card.Cards SpitefulSmith = Card.Cards.CS2_221;          // [5 mana][4/6] Spiteful Smith 
        private const Card.Cards VentureCoMercenary = Card.Cards.CS2_227; 		  // [5 mana][7/6] Venture Co. Mercenary 
        private const Card.Cards StranglethornTiger = Card.Cards.EX1_028;         // [5 mana][5/5] Stranglethorn Tiger 
        private const Card.Cards Abomination = Card.Cards.EX1_097;        // [5 mana][4/4] Abomination 
        private const Card.Cards LeeroyJenkins = Card.Cards.EX1_116;          // [5 mana][6/2] Leeroy Jenkins 
        private const Card.Cards DruidoftheClaw = Card.Cards.EX1_165;         // [5 mana][4/4] Druid of the Claw 
        private const Card.Cards EarthElemental = Card.Cards.EX1_250;         // [5 mana][7/8] Earth Elemental 
        private const Card.Cards AzureDrake = Card.Cards.EX1_284;         // [5 mana][4/4] Azure Drake 
        private const Card.Cards Doomguard = Card.Cards.EX1_310;          // [5 mana][5/7] Doomguard 
        private const Card.Cards HarrisonJones = Card.Cards.EX1_558;          // [5 mana][5/4] Harrison Jones 
        private const Card.Cards FacelessManipulator = Card.Cards.EX1_564;        // [5 mana][3/3] Faceless Manipulator 
        private const Card.Cards Doomhammer = Card.Cards.EX1_567;         // [5 mana][2/8] Doomhammer 
        private const Card.Cards CaptainGreenskin = Card.Cards.NEW1_024;      // [5 mana][5/4] Captain Greenskin 
        private const Card.Cards StampedingKodo = Card.Cards.NEW1_041;    // [5 mana][3/5] Stampeding Kodo 
        private const Card.Cards EtherealConjurer = Card.Cards.LOE_003;           // [5 mana][6/3] Ethereal Conjurer 
        private const Card.Cards NagaSeaWitch = Card.Cards.LOE_038;           // [5 mana][5/5] Naga Sea Witch 
        private const Card.Cards DjinniofZephyrs = Card.Cards.LOE_053;        // [5 mana][4/6] Djinni of Zephyrs 
        private const Card.Cards AnubisathSentinel = Card.Cards.LOE_061;          // [5 mana][4/4] Anubisath Sentinel 
        private const Card.Cards SummoningStone = Card.Cards.LOE_086;         // [5 mana][0/6] Summoning Stone 
        private const Card.Cards EliteTaurenChieftain = Card.Cards.PRO_001;           // [5 mana][5/5] Elite Tauren Chieftain 
        private const Card.Cards SpectralKnight = Card.Cards.FP1_008;         // [5 mana][4/6] Spectral Knight 
        private const Card.Cards SludgeBelcher = Card.Cards.FP1_012;          // [5 mana][3/5] Sludge Belcher 
        private const Card.Cards Stalagg = Card.Cards.FP1_014;        // [5 mana][7/4] Stalagg 
        private const Card.Cards Feugen = Card.Cards.FP1_015;         // [5 mana][4/7] Feugen 
        private const Card.Cards Loatheb = Card.Cards.FP1_030;        // [5 mana][5/5] Loatheb 
        private const Card.Cards Voljin = Card.Cards.GVG_014;         // [5 mana][6/2] Vol'jin 
        private const Card.Cards FelReaver = Card.Cards.GVG_016;          // [5 mana][8/8] Fel Reaver 
        private const Card.Cards KingofBeasts = Card.Cards.GVG_046;           // [5 mana][2/6] King of Beasts 
        private const Card.Cards Quartermaster = Card.Cards.GVG_060;          // [5 mana][2/5] Quartermaster 
        private const Card.Cards CobaltGuardian = Card.Cards.GVG_062;         // [5 mana][6/3] Cobalt Guardian 
        private const Card.Cards BolvarFordragon = Card.Cards.GVG_063;        // [5 mana][1/7] Bolvar Fordragon 
        private const Card.Cards AntiqueHealbot = Card.Cards.GVG_069;         // [5 mana][3/3] Antique Healbot 
        private const Card.Cards SaltyDog = Card.Cards.GVG_070;           // [5 mana][7/4] Salty Dog 
        private const Card.Cards DruidoftheFang = Card.Cards.GVG_080;         // [5 mana][4/4] Druid of the Fang 
        private const Card.Cards UpgradedRepairBot = Card.Cards.GVG_083;          // [5 mana][5/5] Upgraded Repair Bot 
        private const Card.Cards SiegeEngine = Card.Cards.GVG_086;        // [5 mana][5/5] Siege Engine 
        private const Card.Cards OgreNinja = Card.Cards.GVG_088;          // [5 mana][6/6] Ogre Ninja 
        private const Card.Cards MadderBomber = Card.Cards.GVG_090;           // [5 mana][5/4] Madder Bomber 
        private const Card.Cards BombLobber = Card.Cards.GVG_099;         // [5 mana][3/3] Bomb Lobber 
        private const Card.Cards FloatingWatcher = Card.Cards.GVG_100;        // [5 mana][4/4] Floating Watcher 
        private const Card.Cards Junkbot = Card.Cards.GVG_106;        // [5 mana][1/5] Junkbot 
        private const Card.Cards MimironsHead = Card.Cards.GVG_111;           // [5 mana][4/5] Mimiron's Head 
        private const Card.Cards Blingtron3000 = Card.Cards.GVG_119;          // [5 mana][3/4] Blingtron 3000 
        private const Card.Cards HemetNesingwary = Card.Cards.GVG_120;        // [5 mana][6/3] Hemet Nesingwary 
        private const Card.Cards DarkIronSkulker = Card.Cards.BRM_008;        // [5 mana][4/3] Dark Iron Skulker 
        private const Card.Cards DragonConsort = Card.Cards.BRM_018;          // [5 mana][5/5] Dragon Consort 
        private const Card.Cards GrimPatron = Card.Cards.BRM_019;         // [5 mana][3/3] Grim Patron 
        private const Card.Cards BlackwingCorruptor = Card.Cards.BRM_034;         // [5 mana][5/4] Blackwing Corruptor 
        private const Card.Cards RamWrangler = Card.Cards.AT_010;         // [5 mana][3/3] Ram Wrangler 
        private const Card.Cards ShadoPanRider = Card.Cards.AT_028;           // [5 mana][3/7] Shado-Pan Rider 
        private const Card.Cards ThunderBluffValiant = Card.Cards.AT_049;         // [5 mana][3/6] Thunder Bluff Valiant 
        private const Card.Cards MuklasChampion = Card.Cards.AT_090;          // [5 mana][4/3] Mukla's Champion 
        private const Card.Cards ClockworkKnight = Card.Cards.AT_096;         // [5 mana][5/5] Clockwork Knight 
        private const Card.Cards PitFighter = Card.Cards.AT_101;          // [5 mana][5/6] Pit Fighter 
        private const Card.Cards TuskarrJouster = Card.Cards.AT_104;          // [5 mana][5/5] Tuskarr Jouster 
        private const Card.Cards Recruiter = Card.Cards.AT_113;           // [5 mana][5/4] Recruiter 
        private const Card.Cards KvaldirRaider = Card.Cards.AT_119;           // [5 mana][4/4] Kvaldir Raider 
        private const Card.Cards NexusChampionSaraad = Card.Cards.AT_127;         // [5 mana][4/5] Nexus-Champion Saraad 
        private const Card.Cards HolyNova = Card.Cards.CS1_112;           // [5 mana][0/0] Holy Nova 
        private const Card.Cards Bloodlust = Card.Cards.CS2_046;          // [5 mana][0/0] Bloodlust 
        private const Card.Cards Assassinate = Card.Cards.CS2_076;        // [5 mana][0/0] Assassinate 
        private const Card.Cards Nourish = Card.Cards.EX1_164;        // [5 mana][0/0] Nourish 
        private const Card.Cards BaneofDoom = Card.Cards.EX1_320;         // [5 mana][0/0] Bane of Doom 
        private const Card.Cards BlessedChampion = Card.Cards.EX1_355;        // [5 mana][0/0] Blessed Champion 
        private const Card.Cards HolyWrath = Card.Cards.EX1_365;          // [5 mana][0/0] Holy Wrath 
        private const Card.Cards Brawl = Card.Cards.EX1_407;          // [5 mana][0/0] Brawl 
        private const Card.Cards ExplosiveShot = Card.Cards.EX1_537;          // [5 mana][0/0] Explosive Shot 
        private const Card.Cards Starfall = Card.Cards.NEW1_007;      // [5 mana][0/0] Starfall 
        private const Card.Cards ExcavatedEvil = Card.Cards.LOE_111;          // [5 mana][0/0] Excavated Evil 
        private const Card.Cards Demonheart = Card.Cards.GVG_019;         // [5 mana][0/0] Demonheart 
        private const Card.Cards CobraShot = Card.Cards.GVG_073;          // [5 mana][0/0] Cobra Shot 
        private const Card.Cards SolemnVigil = Card.Cards.BRM_001;        // [5 mana][0/0] Solemn Vigil 
        private const Card.Cards DragonsBreath = Card.Cards.BRM_003;          // [5 mana][0/0] Dragon's Breath 
        private const Card.Cards FlameLance = Card.Cards.AT_001;          // [5 mana][0/0] Flame Lance 
        private const Card.Cards FireElemental = Card.Cards.CS2_042;          // [6 mana][6/5] Fire Elemental 
        private const Card.Cards DreadInfernal = Card.Cards.CS2_064;          // [6 mana][6/6] Dread Infernal 
        private const Card.Cards Archmage = Card.Cards.CS2_155;           // [6 mana][4/7] Archmage 
        private const Card.Cards LordoftheArena = Card.Cards.CS2_162;         // [6 mana][6/5] Lord of the Arena 
        private const Card.Cards BoulderfistOgre = Card.Cards.CS2_200;        // [6 mana][6/7] Boulderfist Ogre 
        private const Card.Cards RecklessRocketeer = Card.Cards.CS2_213;          // [6 mana][5/2] Reckless Rocketeer 
        private const Card.Cards TheBlackKnight = Card.Cards.EX1_002;         // [6 mana][4/5] The Black Knight 
        private const Card.Cards SylvanasWindrunner = Card.Cards.EX1_016;         // [6 mana][5/5] Sylvanas Windrunner 
        private const Card.Cards Sunwalker = Card.Cards.EX1_032;          // [6 mana][4/5] Sunwalker 
        private const Card.Cards WindfuryHarpy = Card.Cards.EX1_033;          // [6 mana][4/5] Windfury Harpy 
        private const Card.Cards ArgentCommander = Card.Cards.EX1_067;        // [6 mana][4/2] Argent Commander 
        private const Card.Cards CabalShadowPriest = Card.Cards.EX1_091;          // [6 mana][4/5] Cabal Shadow Priest 
        private const Card.Cards GadgetzanAuctioneer = Card.Cards.EX1_095;        // [6 mana][4/4] Gadgetzan Auctioneer 
        private const Card.Cards CairneBloodhoof = Card.Cards.EX1_110;        // [6 mana][4/5] Cairne Bloodhoof 
        private const Card.Cards FrostElemental = Card.Cards.EX1_283;         // [6 mana][5/5] Frost Elemental 
        private const Card.Cards SavannahHighmane = Card.Cards.EX1_534;           // [6 mana][6/5] Savannah Highmane 
        private const Card.Cards TheBeast = Card.Cards.EX1_577;           // [6 mana][9/7] The Beast 
        private const Card.Cards PriestessofElune = Card.Cards.EX1_583;           // [6 mana][5/4] Priestess of Elune 
        private const Card.Cards IllidanStormrage = Card.Cards.EX1_614;           // [6 mana][7/5] Illidan Stormrage 
        private const Card.Cards TempleEnforcer = Card.Cards.EX1_623;         // [6 mana][6/6] Temple Enforcer 
        private const Card.Cards Kidnapper = Card.Cards.NEW1_005;     // [6 mana][5/3] Kidnapper 
        private const Card.Cards Hogger = Card.Cards.NEW1_040;    // [6 mana][4/4] Hogger 
        private const Card.Cards RenoJackson = Card.Cards.LOE_011;        // [6 mana][4/6] Reno Jackson 
        private const Card.Cards WobblingRunts = Card.Cards.LOE_089;          // [6 mana][2/6] Wobbling Runts 
        private const Card.Cards GelbinMekkatorque = Card.Cards.EX1_112;          // [6 mana][6/6] Gelbin Mekkatorque 
        private const Card.Cards Maexxna = Card.Cards.FP1_010;        // [6 mana][2/8] Maexxna 
        private const Card.Cards TradePrinceGallywix = Card.Cards.GVG_028;        // [6 mana][5/8] Trade Prince Gallywix 
        private const Card.Cards MechBearCat = Card.Cards.GVG_034;        // [6 mana][7/6] Mech-Bear-Cat 
        private const Card.Cards Shieldmaiden = Card.Cards.GVG_053;           // [6 mana][5/5] Shieldmaiden 
        private const Card.Cards IronJuggernaut = Card.Cards.GVG_056;         // [6 mana][6/5] Iron Juggernaut 
        private const Card.Cards AnimaGolem = Card.Cards.GVG_077;         // [6 mana][9/9] Anima Golem 
        private const Card.Cards PilotedSkyGolem = Card.Cards.GVG_105;        // [6 mana][6/4] Piloted Sky Golem 
        private const Card.Cards MogortheOgre = Card.Cards.GVG_112;           // [6 mana][7/6] Mogor the Ogre 
        private const Card.Cards Toshley = Card.Cards.GVG_115;        // [6 mana][5/7] Toshley 
        private const Card.Cards Gazlowe = Card.Cards.GVG_117;        // [6 mana][3/6] Gazlowe 
        private const Card.Cards DrakonidCrusher = Card.Cards.BRM_024;        // [6 mana][6/6] Drakonid Crusher 
        private const Card.Cards VolcanicDrake = Card.Cards.BRM_025;          // [6 mana][6/4] Volcanic Drake 
        private const Card.Cards EmperorThaurissan = Card.Cards.BRM_028;          // [6 mana][5/5] Emperor Thaurissan 
        private const Card.Cards ColdarraDrake = Card.Cards.AT_008;           // [6 mana][6/6] Coldarra Drake 
        private const Card.Cards VoidCrusher = Card.Cards.AT_023;         // [6 mana][5/4] Void Crusher 
        private const Card.Cards WilfredFizzlebang = Card.Cards.AT_027;           // [6 mana][4/4] Wilfred Fizzlebang 
        private const Card.Cards TheMistcaller = Card.Cards.AT_054;           // [6 mana][4/4] The Mistcaller 
        private const Card.Cards MysteriousChallenger = Card.Cards.AT_079;        // [6 mana][6/6] Mysterious Challenger 
        private const Card.Cards MogorsChampion = Card.Cards.AT_088;          // [6 mana][8/5] Mogor's Champion 
        private const Card.Cards SideshowSpelleater = Card.Cards.AT_098;          // [6 mana][6/5] Sideshow Spelleater 
        private const Card.Cards Kodorider = Card.Cards.AT_099;           // [6 mana][3/5] Kodorider 
        private const Card.Cards MasterJouster = Card.Cards.AT_112;           // [6 mana][5/6] Master Jouster 
        private const Card.Cards GrandCrusader = Card.Cards.AT_118;           // [6 mana][5/5] Grand Crusader 
        private const Card.Cards BolfRamshield = Card.Cards.AT_124;           // [6 mana][3/9] Bolf Ramshield 
        private const Card.Cards TheSkeletonKnight = Card.Cards.AT_128;           // [6 mana][7/4] The Skeleton Knight 
        private const Card.Cards SeaReaver = Card.Cards.AT_130;           // [6 mana][6/7] Sea Reaver 
        private const Card.Cards JusticarTrueheart = Card.Cards.AT_132;           // [6 mana][6/3] Justicar Trueheart 
        private const Card.Cards Starfire = Card.Cards.EX1_173;           // [6 mana][0/0] Starfire 
        private const Card.Cards Vanish = Card.Cards.NEW1_004;    // [6 mana][0/0] Vanish 
        private const Card.Cards Blizzard = Card.Cards.CS2_028;           // [6 mana][0/0] Blizzard 
        private const Card.Cards SiphonSoul = Card.Cards.EX1_309;         // [6 mana][0/0] Siphon Soul 
        private const Card.Cards AvengingWrath = Card.Cards.EX1_384;          // [6 mana][0/0] Avenging Wrath 
        private const Card.Cards ForceofNature = Card.Cards.EX1_571;          // [6 mana][0/0] Force of Nature 
        private const Card.Cards HolyFire = Card.Cards.EX1_624;           // [6 mana][0/0] Holy Fire 
        private const Card.Cards Entomb = Card.Cards.LOE_104;         // [6 mana][0/0] Entomb 
        private const Card.Cards Lightbomb = Card.Cards.GVG_008;          // [6 mana][0/0] Lightbomb 
        private const Card.Cards Recycle = Card.Cards.GVG_031;        // [6 mana][0/0] Recycle 
        private const Card.Cards DarkWispers = Card.Cards.GVG_041;        // [6 mana][0/0] Dark Wispers 
        private const Card.Cards DarkBargain = Card.Cards.AT_025;         // [6 mana][0/0] Dark Bargain 
        private const Card.Cards BallofSpiders = Card.Cards.AT_062;           // [6 mana][0/0] Ball of Spiders 
        private const Card.Cards EntertheColiseum = Card.Cards.AT_078;        // [6 mana][0/0] Enter the Coliseum 
        private const Card.Cards GuardianofKings = Card.Cards.CS2_088;        // [7 mana][5/6] Guardian of Kings 
        private const Card.Cards WarGolem = Card.Cards.CS2_186;           // [7 mana][7/7] War Golem 
        private const Card.Cards CoreHound = Card.Cards.CS2_201;          // [7 mana][9/5] Core Hound 
        private const Card.Cards StormwindChampion = Card.Cards.CS2_222;          // [7 mana][6/6] Stormwind Champion 
        private const Card.Cards RavenholdtAssassin = Card.Cards.CS2_161;         // [7 mana][7/5] Ravenholdt Assassin 
        private const Card.Cards GladiatorsLongbow = Card.Cards.DS1_188;          // [7 mana][5/2] Gladiator's Longbow 
        private const Card.Cards AncientofWar = Card.Cards.EX1_178;           // [7 mana][5/5] Ancient of War 
        private const Card.Cards BaronGeddon = Card.Cards.EX1_249;        // [7 mana][7/5] Baron Geddon 
        private const Card.Cards ProphetVelen = Card.Cards.EX1_350;           // [7 mana][7/7] Prophet Velen 
        private const Card.Cards Gorehowl = Card.Cards.EX1_411;           // [7 mana][7/1] Gorehowl 
        private const Card.Cards ArchmageAntonidas = Card.Cards.EX1_559;          // [7 mana][5/7] Archmage Antonidas 
        private const Card.Cards AncientofLore = Card.Cards.NEW1_008;     // [7 mana][5/5] Ancient of Lore 
        private const Card.Cards ObsidianDestroyer = Card.Cards.LOE_009;          // [7 mana][7/7] Obsidian Destroyer 
        private const Card.Cards FlameLeviathan = Card.Cards.GVG_007;         // [7 mana][7/7] Flame Leviathan 
        private const Card.Cards Malorne = Card.Cards.GVG_035;        // [7 mana][9/7] Malorne 
        private const Card.Cards Neptulon = Card.Cards.GVG_042;           // [7 mana][7/7] Neptulon 
        private const Card.Cards Gahzrilla = Card.Cards.GVG_049;          // [7 mana][6/9] Gahz'rilla 
        private const Card.Cards DrBoom = Card.Cards.GVG_110; 		  // [7 mana][7/7] Dr. Boom 
        private const Card.Cards TroggzortheEarthinator = Card.Cards.GVG_118;         // [7 mana][6/6] Troggzor the Earthinator 
        private const Card.Cards RendBlackhand = Card.Cards.BRM_029;          // [7 mana][8/4] Rend Blackhand 
        private const Card.Cards ConfessorPaletress = Card.Cards.AT_018;          // [7 mana][5/4] Confessor Paletress 
        private const Card.Cards FearsomeDoomguard = Card.Cards.AT_020;           // [7 mana][6/8] Fearsome Doomguard 
        private const Card.Cards KnightoftheWild = Card.Cards.AT_041;         // [7 mana][6/6] Knight of the Wild 
        private const Card.Cards Acidmaw = Card.Cards.AT_063;         // [7 mana][4/2] Acidmaw 
        private const Card.Cards SkycapnKragg = Card.Cards.AT_070;        // [7 mana][4/6] Skycap'n Kragg 
        private const Card.Cards EadricthePure = Card.Cards.AT_081;           // [7 mana][3/7] Eadric the Pure 
        private const Card.Cards CapturedJormungar = Card.Cards.AT_102;           // [7 mana][5/9] Captured Jormungar 
        private const Card.Cards Chillmaw = Card.Cards.AT_123;        // [7 mana][6/6] Chillmaw 
        private const Card.Cards Flamestrike = Card.Cards.CS2_032;        // [7 mana][0/0] Flamestrike 
        private const Card.Cards Sprint = Card.Cards.CS2_077;         // [7 mana][0/0] Sprint 
        private const Card.Cards EveryfinisAwesome = Card.Cards.LOE_113;          // [7 mana][0/0] Everyfin is Awesome 
        private const Card.Cards Crush = Card.Cards.GVG_052;          // [7 mana][0/0] Crush 
        private const Card.Cards IronbarkProtector = Card.Cards.CS2_232;          // [8 mana][8/8] Ironbark Protector 
        private const Card.Cards RagnarostheFirelord = Card.Cards.EX1_298;        // [8 mana][8/8] Ragnaros the Firelord 
        private const Card.Cards TirionFordring = Card.Cards.EX1_383;         // [8 mana][6/6] Tirion Fordring 
        private const Card.Cards GrommashHellscream = Card.Cards.EX1_414;         // [8 mana][4/9] Grommash Hellscream 
        private const Card.Cards AlAkirtheWindlord = Card.Cards.NEW1_010;     // [8 mana][3/5] Al'Akir the Windlord 
        private const Card.Cards Gruul = Card.Cards.NEW1_038;     // [8 mana][7/7] Gruul 
        private const Card.Cards FossilizedDevilsaur = Card.Cards.LOE_073;        // [8 mana][8/8] Fossilized Devilsaur 
        private const Card.Cards KelThuzad = Card.Cards.FP1_013;          // [8 mana][6/8] Kel'Thuzad 
        private const Card.Cards ForceTankMAX = Card.Cards.GVG_079;           // [8 mana][7/7] Force-Tank MAX 
        private const Card.Cards FoeReaper4000 = Card.Cards.GVG_113;          // [8 mana][6/9] Foe Reaper 4000 
        private const Card.Cards SneedsOldShredder = Card.Cards.GVG_114;          // [8 mana][5/7] Sneed's Old Shredder 
        private const Card.Cards Chromaggus = Card.Cards.BRM_031;         // [8 mana][6/8] Chromaggus 
        private const Card.Cards Rhonin = Card.Cards.AT_009;          // [8 mana][7/7] Rhonin 
        private const Card.Cards TwistingNether = Card.Cards.EX1_312;         // [8 mana][0/0] Twisting Nether 
        private const Card.Cards LayonHands = Card.Cards.EX1_354;         // [8 mana][0/0] Lay on Hands 
        private const Card.Cards LordJaraxxus = Card.Cards.EX1_323;           // [9 mana][3/15] Lord Jaraxxus 
        private const Card.Cards KingKrush = Card.Cards.EX1_543;          // [9 mana][8/8] King Krush 
        private const Card.Cards Nozdormu = Card.Cards.EX1_560;           // [9 mana][8/8] Nozdormu 
        private const Card.Cards Alexstrasza = Card.Cards.EX1_561;        // [9 mana][8/8] Alexstrasza 
        private const Card.Cards Onyxia = Card.Cards.EX1_562;         // [9 mana][8/8] Onyxia 
        private const Card.Cards Malygos = Card.Cards.EX1_563;        // [9 mana][4/12] Malygos 
        private const Card.Cards Ysera = Card.Cards.EX1_572;          // [9 mana][4/12] Ysera 
        private const Card.Cards Cenarius = Card.Cards.EX1_573;           // [9 mana][5/8] Cenarius 
        private const Card.Cards ArchThiefRafaam = Card.Cards.LOE_092;        // [9 mana][7/8] Arch-Thief Rafaam 
        private const Card.Cards MalGanis = Card.Cards.GVG_021;           // [9 mana][9/7] Mal'Ganis 
        private const Card.Cards MekgineerThermaplugg = Card.Cards.GVG_116;           // [9 mana][9/7] Mekgineer Thermaplugg 
        private const Card.Cards VolcanicLumberer = Card.Cards.BRM_009;           // [9 mana][7/8] Volcanic Lumberer 
        private const Card.Cards MajordomoExecutus = Card.Cards.BRM_027;          // [9 mana][9/7] Majordomo Executus 
        private const Card.Cards Nefarian = Card.Cards.BRM_030;           // [9 mana][8/8] Nefarian 
        private const Card.Cards Anubarak = Card.Cards.AT_036;        // [9 mana][8/4] Anub'arak 
        private const Card.Cards Aviana = Card.Cards.AT_045;          // [9 mana][5/5] Aviana 
        private const Card.Cards NorthSeaKraken = Card.Cards.AT_103;          // [9 mana][9/7] North Sea Kraken 
        private const Card.Cards Icehowl = Card.Cards.AT_125;         // [9 mana][10/10] Icehowl 
        private const Card.Cards TreeofLife = Card.Cards.GVG_033;         // [9 mana][0/0] Tree of Life 
        private const Card.Cards SeaGiant = Card.Cards.EX1_586;           // [10 mana][8/8] Sea Giant 
        private const Card.Cards Deathwing = Card.Cards.NEW1_030;     // [10 mana][12/12] Deathwing 
        private const Card.Cards VarianWrynn = Card.Cards.AT_072;         // [10 mana][7/7] Varian Wrynn 
        private const Card.Cards FrostGiant = Card.Cards.AT_120;          // [10 mana][8/8] Frost Giant 
        private const Card.Cards MindControl = Card.Cards.CS1_113;        // [10 mana][0/0] Mind Control 
        private const Card.Cards Pyroblast = Card.Cards.EX1_279;          // [10 mana][0/0] Pyroblast 
        private const Card.Cards AnyfinCanHappen = Card.Cards.LOE_026;        // [10 mana][0/0] Anyfin Can Happen 
        private const Card.Cards MountainGiant = Card.Cards.EX1_105;          // [12 mana][8/8] Mountain Giant 
        private const Card.Cards ClockworkGiant = Card.Cards.GVG_121;         // [12 mana][8/8] Clockwork Giant 
        private const Card.Cards MoltenGiant = Card.Cards.EX1_620; 		  // [20 mana][8/8] Molten Giant 
        #endregion
        public ProfileParameters GetParameters(Board board) //Current board from the game
        {
            ProfileParameters parameters = new ProfileParameters(BaseProfile.Rush) { GlobalAggroModifier = { Value = 300 } };
            List<Card.Cards> dangerousCards = new List<Card.Cards>{DarnassusAspirant, Mechwarper, PintSizedSummoner, KnifeJuggler /*add more cards here*/};
            //300% of default "Rush" profile value -> the bot will be more aggressive

            if (board.TurnCount < 6 || board.HeroEnemy.CurrentHealth > 12) //If current turn < 6 or enemy's hp > 12
            {
                //Set lightning bolt spell modifier to 250% of the base spell value defined in "Rush" profile, the bot will try to keep this spell in hand before turn 6
                parameters.SpellsModifiers.Rules.Add(LightningBolt, new Range(250));

                //Set crackle spell modifier to 250% of the base spell value defined in "Rush" profile, the bot will try to keep this spell in hand before turn 6
                parameters.SpellsModifiers.Rules.Add(Crackle, new Range(250));

                //Set lava burst spell modifier to 250% of the base spell value defined in "Rush" profile, the bot will try to keep this spell in hand before turn 6
                parameters.SpellsModifiers.Rules.Add(LavaBurst, new Range(250));
            }

            if (board.WeaponFriend == null || !(board.HeroEnemy.CurrentHealth + board.HeroEnemy.CurrentArmor <= 3)) //If we don't have doomhammer this turn
            {
                //Set rockbiter spell modifier to 350% of the base spell value defined in "Rush" profile, the bot will try to keep this spell in hand
                parameters.SpellsModifiers.Rules.Add(Card.Cards.CS2_045, new Range(350));
            }

            if (board.OverloadedMana == 0 && board.LockedMana == 0) //If we don't have any overloaded or locked crystals
            {
                //Set lava shock spell modifier to 250% of the base spell value defined in "Rush" profile, the bot will try to keep this spell in hand without any overloaded mana
                parameters.SpellsModifiers.Rules.Add(Card.Cards.BRM_011, new Range(250));
            }

            return parameters;
        }
    }
}